sudo: required
distro: xenial

addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chefdk

install: echo "skip bundle install"

#branches:
#  only:
#    - master

before_script:
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

#  - chef exec delivery local all
script:
  - chef exec delivery local verify
  - rubocop
